# Generated by Django 2.2.4 on 2020-10-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20201009_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book_thing',
            new_name='books',
        ),
    ]
